export const works = [
  {
    slug: "rag-document-chat",
    title: "RAG Document Chat",
    tagline: "Chat with your private documents using retrieval-augmented generation.",
    category: "AI/ML",
    featured: true,
    year: "2025",
    image: "/images/works/rag-chat.png",
    tags: ["Python", "OpenAI", "LangChain", "Vector DB", "FastAPI"],
    link: "#",
    github: "#",
    overview:
      "A production-ready RAG system that lets users upload private PDFs and chat with them using natural language. Built to solve the problem of extracting knowledge from unstructured documents without leaking data to third-party services.",
    highlights: [
      "Document ingestion pipeline with chunking and embedding generation",
      "Vector search using cosine similarity over embedded chunks",
      "Streaming responses with source citations for every answer",
      "FastAPI backend with rate limiting and session management",
    ],
    stack: ["Python", "OpenAI API", "LangChain", "FAISS", "FastAPI", "Next.js"],
  },
  {
    slug: "agentic-workflow-automation",
    title: "Agentic Workflow Automation",
    tagline: "Multi-step LLM agents that automate research and reporting tasks.",
    category: "AI/ML",
    featured: false,
    year: "2025",
    image: "/images/works/agentic.png",
    tags: ["Python", "OpenAI", "Agents", "Tool Use"],
    link: "#",
    github: "#",
    overview:
      "An agentic system that breaks down complex research tasks into steps, uses tools (web search, file I/O, APIs), and produces structured reports autonomously.",
    highlights: [
      "Tool-calling agents with reasoning loops",
      "Structured output validation with retries",
      "Multi-agent orchestration for parallel subtasks",
    ],
    stack: ["Python", "OpenAI Functions", "Pydantic", "FastAPI"],
  },
  {
    slug: "mern-ecommerce",
    title: "MERN E-Commerce Platform",
    tagline: "Full-stack store with auth, cart, payments, and admin dashboard.",
    category: "Full-Stack",
    featured: false,
    year: "2024",
    image: "/images/works/ecommerce.png",
    tags: ["React", "Node.js", "MongoDB", "Express"],
    link: "#",
    github: "#",
    overview:
      "A complete e-commerce application built during my internship at SkillifyZone. Handles product listings, cart state, checkout flow, and admin product management.",
    highlights: [
      "JWT-based authentication with refresh tokens",
      "MongoDB schemas optimized for product queries",
      "RESTful API with Express middleware chain",
      "Responsive React UI with state management",
    ],
    stack: ["React", "Node.js", "Express", "MongoDB", "Tailwind"],
  },
  {
    slug: "task-manager",
    title: "Realtime Task Manager",
    tagline: "Collaborative task board with live updates across users.",
    category: "Full-Stack",
    featured: false,
    year: "2024",
    image: "/images/works/taskmanager.png",
    tags: ["Next.js", "Socket.io", "MongoDB"],
    link: "#",
    github: "#",
    overview:
      "A Kanban-style task manager with real-time sync — when one user moves a card, every other user sees it instantly.",
    highlights: [
      "Socket.io for realtime bidirectional updates",
      "Drag-and-drop Kanban board",
      "Optimistic UI updates for snappy feel",
    ],
    stack: ["Next.js", "Socket.io", "MongoDB", "Tailwind"],
  },
  {
    slug: "analytics-dashboard",
    title: "Analytics Dashboard",
    tagline: "Data visualization dashboard for tracking product metrics.",
    category: "Full-Stack",
    featured: false,
    year: "2024",
    image: "/images/works/analytics.png",
    tags: ["React", "Express", "Charts"],
    link: "#",
    github: "#",
    overview:
      "A clean analytics dashboard with charts, filters, and exportable reports. Built to demonstrate full-stack data handling.",
    highlights: [
      "Interactive charts with filters and time ranges",
      "Aggregation pipelines in MongoDB",
      "CSV export for reports",
    ],
    stack: ["React", "Express", "MongoDB", "Recharts"],
  },
];

export const categories = ["All", "AI/ML", "Full-Stack"];